name: imprimir contenedores intento 3

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu/lastest
    steps:
    - name: test aws
      env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
      run: aws s3 ls
    
